### ISSUE TITLE
File system support 

### ISSUE THREAD

**Issue by writemonkey** [writemonkey/wm3#18]
Only local database is supported at the moment.

**Comment by archetyped** [comment]
This feature is particularly important as all of my existing writing is stored in text files.  A program-agnostic file-based approach is also necessary for allowing access to the content on multiple platforms (desktop, mobile) using different editors.

**Comment by Kensai2000** [comment]
Taking a page from ResophNotes, again, which uses a database to perform its search functionality, even when you've selected the use of plain text files in the option, I'm imagining you're going to want to go with something along those lines.

WM3 will not likely be able to function with useable reaction times without retaining the database as its core mode of dealing with the data. As a background process, likely focused on but not solely relegated to opening and closing of the application, WM3 will be responsible for parsing differences between its database and its designated assortment of text files, and updating in both directions as appropriate.

This sort of redundant storage system will give WM3 and the work of anyone who uses it maximum flexibility. Even with coverage for Win/Lin/OSX, the most common platforms are actually iOS/Android. Having your work as a collection of text files on, say, Dropbox, allows you to access/edit/create files in your "workspace". For example, I would set up an action in Drafts on my trusty iPod touch that would send whatever I thumbed into a file, plus maybe a time/date stamp into a specified folder on Dropbox as a TXT file that would later show up in WM3's file management when I'm actually able to sit at a real keyboard and work.

The possibilities are wide ranging.

A foreseeable issue would be not knowing how you're going to end up implementing project management, so if you were to come up with ways of explicitly group files in WM3 (something assigned by drag & drop or some keyboard equivalent) you would probably want your file system to support subfoldering so that this implicit division could easily be read by someone looking at files and folders in a more traditional manner (i.e. File Explorer et al).

**Comment by writemonkey** [comment]
Yes, files will also be saved as database entries and wm will keep them in sync. I am not yet sure how to implement this. As you said, possibilities are wide ranging.
