### ISSUE TITLE
Inconsistency: markdown preview can't be closed by clicking the edge of the screen

### ISSUE THREAD

**Issue by lukemicallef** [writemonkey/wm3#194]
The repository and wordnik plugins allow the sidebar to be closed by clicking the right edge of the screen. The markdown preview plugin, which appears in the same space, does not seem to allow this.

**Comment by writemonkey** [comment]
Hi, can't reproduce this one. I can always close preview by clicking the right edge. The preview has a problem with resizing (one can only resize it by dragging top or bottom edge). I figure your problem is somehow connected to that. 
Does mouse pointer (when preview is opened and mouse is over the edge) change to a hand?
i.

**Comment by lukemicallef** [comment]
You know what, this has been bugging me for months. Turns out I was clicking the wrong side of the preview scrollbar - I haven't come across the scrollbar on the repo and wordnik sidebars. Sorry. 

Worth noting that on a small screen (12"/1080p) the active area between the scrollbar and the edge of the screen is very small.

**Comment by writemonkey** [comment]
Next version will have a setting to scale all UI elements to a desired size.
i.
