### ISSUE TITLE
Feature request: Per-document repository

### ISSUE THREAD

**Issue by ajsteele** [writemonkey/wm3#206]
I think it would be really useful if notes in the repository had three settings: the default would be per-document, ie not project-wide as they are at the moment; then per-project, as it is currently; and then global, as is an option currently.

In a longer manuscript spread over several documents (eg, chapters of a book) this would allow me to keep track of notes relevant to each chapter (document) much more easily.

**Comment by philmayes** [comment]
I have found a kind of workaround for this. When a document is selected via All or Today, the repository only shows snippets saved from that document. When it is selected via Projects:My-project, project-wide snippets are shown. (It took me some time to work out why the repository appeared inconsistent!)

It's still a little inconsistent because of caching. If you switch between Projects:X and Today and the document remains selected (i.e. it is the most recently edited), the repository contents will not change.

**Comment by writemonkey** [comment]
Will add this for the new release.
i.

**Comment by ajsteele** [comment]
Thanks! Looking forward to it 👍

**Comment by writemonkey** [comment]
Done!
i.
