### ISSUE TITLE
Add "Save As..." to the Command Palette

### ISSUE THREAD

**Issue by snoozysoft** [writemonkey/wm3#271]
Considering "Save" doesn't actually export to a file, it's a bit confusing to have to right click on the document on the sidebar and click "Bind to File" just so that I have a copy outside of Writemonkey. For accessibility reasons and for the sake of peace of mind in case something goes wrong in Writemonkey itself, it would be nice to have an easier and more immediately obvious choice to save our work to a file in the Command Palette.

**Comment by jmcd040** [comment]
I made a suggestions similar to this (#263). I'm wondering if when you use "Save as" in your scenario would the file be bound to it from then on? I was suggesting that when the doc is bound to an outside file, perhaps the name of the file could be in the meta-data at the top of the document. If it was edited, the program would rename the file in the computer's file system.

**Comment by snoozysoft** [comment]
Yeah, I'd say binding it to the file at the same time would make sense so it fits into Writemonkey's ecosystem or whatever you wanna call it. 

Basically sort of just reducing a step or two when it comes to saving your work in it as if WM was a regular text editor, since its not immediately obvious how saving in it works.

**Comment by Nootilus** [comment]
I also agree. I really don’t get the point in having to bind a document to a file. It’s really confusing to me.
And, even if I manage to find a use of this operation, I think that a kind of quick way to do that via a "save as…" option would be great.

**Comment by jmcd040** [comment]
So if I may speak for the WM "ecosystem," documents are first and foremost created in a WM database. Collections of documents can then be organized into projects. Documents in the database can also be located by searching by content including meta-data like tags. This allows the user to create documents without concern of where they are stored in any media structure. If find that frees me to create documents as I think of them, or test an idea.  
"Binding" a document to a "file" makes a one-to-one connection between the document content in the database and an external file. I can think of three reasons to do this:
1. Security of knowing the file is not tied up in some proprietary database.
2. Sharing the file
3. Editing the document with another program. For example I've used Notepad++ to search and replace with regular expressions and I've experimented with editing the document in Typora. I find Typora more pleasing to edit with since it renders markup rather than requiring a "preview pane", does images more consistently and creates PDFs that turns headings into bookmarks in the PDF. However WM has the repository which I like a lot (especially macros and links), project organization and handles tables in a way that is far less confusing.
Whatever the reason, if the file gets edited then WM will update its database and vice versa so the database document and file are tightly linked, i.e. "bound."
