### ISSUE TITLE
Add a to-do list or outline pane in the right sidebar

### ISSUE THREAD

**Issue by snoozysoft** [writemonkey/wm3#272]
It would be rather convenient if we could keep a little list of tasks of say, "things to mention", when writing in the app. Specifically It'd be separate from a given file but attached to it, i.e. only visible in the right-hand sidebar but not the main bit in the middle where all the writing happens. 

So, for example, say I'm writing an article about Bees. I want to make sure I mention a few related topics, such as our overall ecosystem, the fact that we need to make an effort to save them, what benefits they bring to us and how to discern them from other yellow & black flying insects. I could jot down all those topics in the right sidebar to remind me to mention them somewhere in the article and occasionally glance over at it as I'm busy writing away.

**Comment by writemonkey** [comment]
If you don't want to use in-document tasks `- [ ] some task`, you can always use repository. For each task a separate repo entry. When task is finished, you can choose Strike-through to mark it as done. 
i.

**Comment by snoozysoft** [comment]
Ah, I didn't know the repository existed! That sounds like it'll be ideal, thank you.

**Comment by jmcd040** [comment]
I tried using the repository for task items, but gave up for two reasons.
1. The task items got lost in the repository list because the repo list is a push-down list that puts the latest item at the top, so some items keep moving off the bottom. If I could keep it sorted with task items at the top and clickable link items next it would be more useful. 
2. It would be nice if task items in the repository could be tied to spots in the document. I like the little icons you put for bookmarks, if you had something like that for task items in the repository that would work well. The problem with putting task items inside the document is they get counted in the word count so an alternative could be to not count any task items, but then you might have to have a special task item in case someone wanted the tasks to be part of the document word count.
