### ISSUE TITLE
Should be possible to set editor font

### ISSUE THREAD

**Issue by erokar** [writemonkey/wm3#59]
Correct me if I'm wrong, but seems you can only set the print font in the settings.

**Comment by writemonkey** [comment]
Fonts can be defined in themes. Open desired theme file, find `$wm-editor` selector and change `font-family` property.  You can use any installed font but I recommend mono spaced fonts.

**Comment by sergeevabc** [comment]
It is difficult to put into words how inconvenient it is not to be able to set a preferred font via a dialog box. One has to search for the font's full name in order to type it into some WM3 file.

Also, it's not enough just to add, for example, `font-family: DMCA Sans Serif;` into theme CSS file, because some other ugly font (e.g. Hack Mono) is used by default. so one has to add `!important` as well, e.g. `font-family: DMCA Sans Serif !important;`.
